"""Add additional_info column to mentor_profile

Revision ID: 03ee28c3270f
Revises: 
Create Date: 2025-09-02 10:35:51.600956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ee28c3270f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###
