"""Add task assignments table

Revision ID: 187c354c4caf
Revises: f8ad82d3fc41
Create Date: 2025-11-09 01:36:15.908188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187c354c4caf'
down_revision = 'f8ad82d3fc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentee_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['signup_details.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['signup_details.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['MasterTask.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentee_tasks')
    # ### end Alembic commands ###
