"""Remove institution_profile table

Revision ID: 1e6387d6ef39
Revises: c22c5a3ede3d
Create Date: 2025-11-29 01:27:36.518145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6387d6ef39'
down_revision = 'c22c5a3ede3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('designation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('department', sa.VARCHAR(length=100), nullable=True),
    sa.Column('official_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('total_students', sa.INTEGER(), nullable=True),
    sa.Column('total_mentors', sa.INTEGER(), nullable=True),
    sa.Column('active_mentorships', sa.INTEGER(), nullable=True),
    sa.Column('receive_reports', sa.BOOLEAN(), nullable=True),
    sa.Column('report_frequency', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['signup_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
