"""Update institution profile management

Revision ID: 20260206_update_institution_profile_management
Revises: f80b6651fd97
Create Date: 2026-02-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260206_update_institution_profile_management'
down_revision = 'f80b6651fd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Clean up orphaned institutions (those without user_id)
    op.execute("DELETE FROM institutions WHERE user_id IS NULL")
    
    # Step 2: For SQLite, we need to recreate the table to remove columns and make user_id NOT NULL
    # Create new table structure
    op.create_table('institutions_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('email_domain', sa.String(length=100), nullable=True),
        sa.Column('contact_person', sa.String(length=100), nullable=True),
        sa.Column('contact_phone', sa.String(length=20), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('website', sa.String(length=200), nullable=True),
        sa.Column('institution_type', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('profile_picture', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['signup_details.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    
    # Step 3: Copy data from old table to new table (excluding name and contact_email)
    op.execute("""
        INSERT INTO institutions_new (
            id, user_id, email_domain, contact_person, contact_phone, 
            address, city, state, country, website, institution_type, 
            status, profile_picture, created_at
        )
        SELECT 
            id, user_id, email_domain, contact_person, contact_phone,
            address, city, state, country, website, institution_type,
            status, profile_picture, created_at
        FROM institutions
        WHERE user_id IS NOT NULL
    """)
    
    # Step 4: Drop old table and rename new table
    op.drop_table('institutions')
    op.rename_table('institutions_new', 'institutions')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Recreate the old table structure
    op.create_table('institutions_old',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('email_domain', sa.String(length=100), nullable=True),
        sa.Column('contact_person', sa.String(length=100), nullable=True),
        sa.Column('contact_email', sa.String(length=100), nullable=True),
        sa.Column('contact_phone', sa.String(length=20), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('country', sa.String(length=100), nullable=True),
        sa.Column('website', sa.String(length=200), nullable=True),
        sa.Column('institution_type', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('profile_picture', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['signup_details.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('user_id')
    )
    
    # Copy data back and populate name and contact_email from User records
    op.execute("""
        INSERT INTO institutions_old (
            id, user_id, name, email_domain, contact_person, contact_email, contact_phone,
            address, city, state, country, website, institution_type,
            status, profile_picture, created_at
        )
        SELECT 
            i.id, i.user_id, u.name, i.email_domain, i.contact_person, u.email, i.contact_phone,
            i.address, i.city, i.state, i.country, i.website, i.institution_type,
            i.status, i.profile_picture, i.created_at
        FROM institutions i
        JOIN signup_details u ON i.user_id = u.id
    """)
    
    # Drop new table and rename old table back
    op.drop_table('institutions')
    op.rename_table('institutions_old', 'institutions')
    
    # ### end Alembic commands ###