"""add_linkedin_link_to_mentee_profile

Revision ID: 20260208_add_linkedin_link
Revises: 20260206_update_institution_profile_management
Create Date: 2026-02-08 19:06:47.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260208_add_linkedin_link'
down_revision = '20260206_update_institution_profile_management'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin_link', sa.String(200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentee_profile', schema=None) as batch_op:
        batch_op.drop_column('linkedin_link')

    # ### end Alembic commands ###
