"""Add mentor_id to PersonalTask

Revision ID: 356425c36bc8
Revises: 3f2ce0d62ffc
Create Date: 2025-11-09 12:46:31.208193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356425c36bc8'
down_revision = '3f2ce0d62ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mentor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_personal_tasks_mentor_id',  # ✅ CONSTRAINT NAME ADDED
            'signup_details', 
            ['mentor_id'], 
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mentor_id')

    # ### end Alembic commands ###
