"""Add task assignments table

Revision ID: 385b45de0060
Revises: 901747dc37f4
Create Date: 2025-11-08 03:15:51.965072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385b45de0060'
down_revision = '901747dc37f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentorship_request_id', sa.Integer(), nullable=False),
    sa.Column('master_task_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['master_task_id'], ['MasterTask.id'], ),
    sa.ForeignKeyConstraint(['mentorship_request_id'], ['mentorship_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks_assigned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.drop_column('tasks_assigned')

    op.drop_table('task_assignments')
    # ### end Alembic commands ###
