"""add institution_id foreign key to user

Revision ID: 45cd7a873c47
Revises: 5eba084a9b70
Create Date: 2025-11-30 23:53:15.178958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cd7a873c47'
down_revision = '5eba084a9b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_signup_details_institution_id', 'institutions', ['institution_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_details', schema=None) as batch_op:
        batch_op.drop_constraint('fk_signup_details_institution_id', type_='foreignkey')
        batch_op.drop_column('institution_id')

    # ### end Alembic commands ###
