"""Add progress column to MenteeTask

Revision ID: 59df0a753abc
Revises: 356425c36bc8
Create Date: 2025-11-09 13:32:13.720864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59df0a753abc'
down_revision = '356425c36bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentee_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentee_tasks', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
