"""update institution table

Revision ID: 5eba084a9b70
Revises: 1e6387d6ef39
Create Date: 2025-11-30 22:56:14.925087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eba084a9b70'
down_revision = '1e6387d6ef39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_column('institution_type')

    # ### end Alembic commands ###
