"""add user_id to institution

Revision ID: 86b878526589
Revises: 45cd7a873c47
Create Date: 2025-12-01 00:16:41.971461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b878526589'
down_revision = '45cd7a873c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_institutions_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_institutions_user_id', 'signup_details', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_institutions_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_institutions_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
