"""Add MasterTask table

Revision ID: 901747dc37f4
Revises: ff0a3d9f29b7
Create Date: 2025-11-07 20:12:14.680423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901747dc37f4'
down_revision = 'ff0a3d9f29b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MasterTask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=50), nullable=False),
    sa.Column('journey_phase', sa.String(length=200), nullable=False),
    sa.Column('purpose_of_call', sa.Text(), nullable=False),
    sa.Column('mentor_focus', sa.Text(), nullable=False),
    sa.Column('mentee_focus', sa.Text(), nullable=False),
    sa.Column('program_incharge_actions', sa.Text(), nullable=False),
    sa.Column('meeting_plan_overview', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MasterTask')
    # ### end Alembic commands ###
