"""Add institution and institution_other fields to mentee_profile

Revision ID: add_institution_mentee
Revises: 
Create Date: 2025-01-23 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_institution_mentee'
down_revision = '799b4c439b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('institution_other', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentee_profile', schema=None) as batch_op:
        batch_op.drop_column('institution_other')
        batch_op.drop_column('institution')

    # ### end Alembic commands ###
