"""initial

Revision ID: c22c5a3ede3d
Revises: 31f9f2e0116e
Create Date: 2025-11-23 16:06:38.015282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22c5a3ede3d'
down_revision = '31f9f2e0116e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email_domain', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('institution_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('official_phone', sa.String(length=20), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('total_mentors', sa.Integer(), nullable=True),
    sa.Column('active_mentorships', sa.Integer(), nullable=True),
    sa.Column('receive_reports', sa.Boolean(), nullable=True),
    sa.Column('report_frequency', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['signup_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('signup_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signup_details', schema=None) as batch_op:
        batch_op.drop_column('institution')

    op.drop_table('institution_profile')
    op.drop_table('institutions')
    # ### end Alembic commands ###
