"""Add years of expireance

Revision ID: cac9ecc791ba
Revises: 
Create Date: 2025-09-08 15:23:52.085388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac9ecc791ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_of_experience', sa.String(length=100), nullable=True))
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mentor_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('years_of_experience')

    # ### end Alembic commands ###
