"""empty message

Revision ID: d7110d158872
Revises: cac9ecc791ba
Create Date: 2025-09-18 06:12:40.347464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7110d158872'
down_revision = 'cac9ecc791ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentorship_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentee_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('meeting_time', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('meeting_type', sa.String(length=50), nullable=True),
    sa.Column('purpose_type', sa.String(length=50), nullable=True),
    sa.Column('why_need_mentor', sa.Text(), nullable=False),
    sa.Column('mentor_status', sa.String(length=20), nullable=True),
    sa.Column('supervisor_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['signup_details.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['signup_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentorship_requests')
    # ### end Alembic commands ###
