"""Add task assignments table2

Revision ID: f8ad82d3fc41
Revises: 385b45de0060
Create Date: 2025-11-08 13:17:51.416071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ad82d3fc41'
down_revision = '385b45de0060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_assignments')
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.drop_column('tasks_assigned')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasks_assigned', sa.BOOLEAN(), nullable=True))

    op.create_table('task_assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mentorship_request_id', sa.INTEGER(), nullable=False),
    sa.Column('master_task_id', sa.INTEGER(), nullable=False),
    sa.Column('assigned_date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('completed_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['master_task_id'], ['MasterTask.id'], ),
    sa.ForeignKeyConstraint(['mentorship_request_id'], ['mentorship_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
