"""Add meet_link and gcal_event_id to MeetingRequest

Revision ID: ff0a3d9f29b7
Revises: 568488c98253
Create Date: 2025-10-12 12:10:01.496140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0a3d9f29b7'
down_revision = '568488c98253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('gcal_event_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.drop_column('gcal_event_id')
        batch_op.drop_column('meet_link')

    # ### end Alembic commands ###
